name: Python package

on: [push]

jobs:
  build:

    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4
      - name: Install libxkbregistry-dev
        run: |
          sudo apt-get install libxkbregistry-dev
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install --edit .
      - name: Lint with flake8
        run: |
          flake8 xkbregistry tests
      - name: Test with pytest
        run: |
          pytest
